# UpData - História legal, agora me mostre os dados!
Somos a UpData e começamos nossa jornada fornecendo consultoria de empresas e implementando a cultura 
data driven criando assim métricas que melhoram o marketing e faturamento da empresa.
 
Hoje, estamos trabalhando com uma empresa chamada 'WeAvocado', uma empresa grande que existe desde 2015 e em
2018 nos aliamos para fornecemos nosssos serviços, tendo em vista o decrescente faturamento da empresa.

In [0]:
#Importando a tabela
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import datetime, date, time
from sklearn.preprocessing import MinMaxScaler

df = spark.read.csv("/FileStore/tables/avocado.csv", header=True, sep=",")
df = df.toPandas()
df.head()

,_c0,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2,2015-12-13,0.93,118220.22,794.7,109149.67,130.5,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,3,2015-12-06,1.08,78992.15,1132.0,71976.41,72.58,5811.16,5677.4,133.76,0.0,conventional,2015,Albany
4,4,2015-11-29,1.28,51039.6,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany

In [0]:
#Formatar colunas e tratar dados
df.rename(columns={'_c0': 'index'}, inplace = True)
df.head()

,index,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
18244,7,2018-02-04,1.63,17074.83,2046.96,1529.2,0.0,13498.67,13066.82,431.85,0.0,organic,2018,WestTexNewMexico
18245,8,2018-01-28,1.71,13888.04,1191.7,3431.5,0.0,9264.84,8940.04,324.8,0.0,organic,2018,WestTexNewMexico
18246,9,2018-01-21,1.87,13766.76,1191.92,2452.79,727.94,9394.11,9351.8,42.31,0.0,organic,2018,WestTexNewMexico
18247,10,2018-01-14,1.93,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.0,0.0,organic,2018,WestTexNewMexico
18248,11,2018-01-07,1.62,17489.58,2894.77,2356.13,224.53,12014.15,11988.14,26.01,0.0,organic,2018,WestTexNewMexico

In [0]:
df2 = df.filter(['4046', '4225', '4770', 'year', 'Small Bags', 'Large Bags', 'XLarge Bags'])
df2["year"] = df2["year"].astype(int)
df2["4046"] = df2["4046"].astype(float)
df2["4225"] = df2["4225"].astype(float)
df2["4770"] = df2["4770"].astype(float)
df2["Small Bags"] = df2["Small Bags"].astype(float)
df2["Large Bags"] = df2["year"].astype(float)
df2["XLarge Bags"] = df2["XLarge Bags"].astype(float)

df2 = df2.groupby('year').agg(
    Pequeno=('4046','mean'),
    Medio=('4225','mean'),
    Grande=('4770','mean'),
    SmallBags=('Small Bags','mean'),
    LargeBags=('Large Bags','mean'),
    XLargeBags=('XLarge Bags','mean')
    ).reset_index()
df2

,year,Pequeno,Medio,Grande,SmallBags,LargeBags,XLargeBags
0,2015,304443.451708,313633.844367,25426.962520,113033.429256,2015.0,969.390611
1,2016,271567.466578,297850.478632,28468.633371,197025.327568,2016.0,3568.070662
2,2017,288716.905194,269964.124350,15941.542779,213728.158838,2017.0,4193.843471
3,2018,355323.868904,314628.606698,17694.903387,278349.820795,2018.0,5563.728295

In [0]:
df2 = df2/1000
df2["year"] = df2["year"]*1000
df2 = df2.astype(int)

COLUNAS = ['Ano','Media','Classe']
new = pd.DataFrame(columns=COLUNAS)

def adicionar(classe, inicia):
    novaBase = df2.filter(['year', classe])
    novaBase["Classe"] = classe
    
    for i, infos in novaBase.iterrows():
        new.loc[inicia] = [infos[0], infos[1], infos[2]]
        inicia += 1
    
adicionar("Pequeno", 0)
adicionar("Medio", 4)
adicionar("Grande", 8)
adicionar("SmallBags", 12)
adicionar("LargeBags", 16)
adicionar("XLargeBags", 20)

new.head()

,Ano,Media,Classe
0,2015,304,Pequeno
1,2016,271,Pequeno
2,2017,288,Pequeno
3,2017,355,Pequeno
4,2015,313,Medio

In [0]:
new

,Ano,Media,Classe
0,2015,304.0,Pequeno
1,2016,271.0,Pequeno
2,2017,288.0,Pequeno
3,2017,355.0,Pequeno
4,2015,313.0,Medio
5,2016,297.0,Medio
6,2017,269.0,Medio
7,2017,314.0,Medio
8,2015,25.0,Grande
9,2016,28.0,Grande
10,2017,15.0,Grande
11,2017,17.0,Grande
12,2015,113.0,SmallBags
13,2016,197.0,SmallBags
14,2017,213.0,SmallBags
15,2017,278.0,SmallBags
16,2015,2.0,LargeBags
17,2016,2.0,LargeBags
18,2017,2.0,LargeBags
19,2017,2.0,LargeBags
20,2015,0.0,XLargeBags
21,2016,3.0,XLargeBags
22,2017,4.0,XLargeBags
23,2017,5.0,XLargeBags

In [0]:
# new["Ano"] = new["Ano"].astype(int)
# new["Media"] = new["Media"].astype(float)
# new.info()

# new.filter(['Ano', 'Media']).reset_index().unstack().plot.bar(color='red',ec ='k', stacked = True);
sns.barplot(new, x='Media', y='Ano')

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<command-2526847955093337> in <cell line: 6>()
      4
      5 # new.filter(['Ano', 'Media']).reset_index().unstack().plot.bar(color='red',ec ='k', stacked = True);
----> 6 sns.barplot(new, x='Media', y='Ano')

/databricks/python/lib/python3.9/site-packages/seaborn/_decorators.py in inner_f(*args, **kwargs)
     44             )
     45         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 46         return f(**kwargs)
     47     return inner_f
     48

/databricks/python/lib/python3.9/site-packages/seaborn/categorical.py in barplot(x, y, hue, data, order, hue_order, estimator, ci, n_boot, units, seed, orient, color, palette, saturation, errcolor, errwidth, capsize, dodge, ax, **kwargs)
   3180 ):
   3181
-> 3182     plotter = _BarPlotter(x, y, hue, data, order, hue_order,
   3183                           estimator, ci, n_boot, units, seed,
   3184                           orient, color, palette, saturation,

/databricks/python/lib/python3.9/site-packages/seaborn/categorical.py in __init__(self, x, y, hue, data, order, hue_order, estimator, ci, n_boot, units, seed, orient, color, palette, saturation, errcolor, errwidth, capsize, dodge)
   1582                  errwidth, capsize, dodge):
   1583         """Initialize the plotter."""
-> 1584         self.establish_variables(x, y, hue, data, orient,
   1585                                  order, hue_order, units)
   1586         self.establish_colors(color, palette, saturation)

/databricks/python/lib/python3.9/site-packages/seaborn/categorical.py in establish_variables(self, x, y, hue, data, orient, order, hue_order, units)
    151                 if isinstance(var, str):
    152                     err = "Could not interpret input '{}'".format(var)
--> 153                     raise ValueError(err)
    154
    155             # Figure out the plotting orientation

ValueError: Could not interpret input 'Ano'

Referências
https://www.kaggle.com/datasets/neuromusic/avocado-prices